version: '3.8'
services:

  keycloak:
    image: jboss/keycloak:16.1.0
    ports:
      - 8090:8080
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: db_keycloak
      DB_PORT: 3306
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak/realms/realm-export.json:/tmp/realm-export.json
    depends_on:
      - database_keycloak
    networks:
      - common-network
      
  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: staff-api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - common-network

  database_keycloak:
    image: mysql:8.0
    ports:
      - "3309:3306"
    container_name: db_keycloak
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
    volumes:
      - keycloak-volume:/var/lib/mysql
    networks:
      - common-network


networks:
  common-network:
      driver: bridge


volumes:
  .m2:
  keycloak-volume:
  mysql-volume:
